Add missing dependencies
```
❯ cargo test
   Compiling rand v0.4.2
   Compiling env_logger v0.4.3
   Compiling mio-named-pipes v0.1.5 (file:///home/hugh/tmp/mio-named-pipes)
error[E0463]: can't find crate for `mio`
 --> tests/smoke.rs:1:1
  |
1 | extern crate mio;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `mio-named-pipes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```